Trying to fix the project manually, missing:
missing to fix:
Execution failed for task ':app:hiltJavaCompileDebug'.
> java.lang.IllegalStateException: Unable to read Kotlin metadata due to unsupported metadata version.